const menuItems = [
  {
    id: 1,
    name: 'Art',
    subItems: [
      {
        id: 1,
        namePlissee: 'Plissee nach Maß',
        nameRollos: 'Rollos nach Maß',
        imgPlissee: 'icons/arten/plissee_nach_mass.svg',
        imgRollos: 'icons/arten/plissee_nach_mass.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 2,
        namePlissee: 'Cosimo',
        nameRollos: 'Cosimo',
        imgPlissee: 'icons/arten/cosimo.svg',
        imgRollos: 'icons/arten/cosimo.svg',
        linkplissee: 'y',
        linkRollos: '',
        plissee: true,
        rollos: false,
      },
      {
        id: 3,
        namePlissee: 'Cosiflor',
        nameRollos: 'Cosiflor',
        imgPlissee: 'icons/arten/cosiflor.svg',
        imgRollos: 'icons/arten/cosiflor.svg',
        linkplissee: 'y',
        linkRollos: '',
        plissee: true,
        rollos: false,
      },
      {
        id: 4,
        namePlissee: 'Decomatic',
        nameRollos: 'Decomatic',
        imgPlissee: 'icons/arten/decomatic.svg',
        imgRollos: 'icons/arten/decomatic.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: false,
      },
      {
        id: 5,
        namePlissee: 'Wabenplissee',
        nameRollos: 'Wabenplissee',
        imgPlissee: 'icons/arten/wabenplissee.svg',
        imgRollos: 'icons/arten/wabenplissee.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: false,
      },
      {
        id: 6,
        namePlissee: 'Doppelplissee',
        nameRollos: 'Doppelplissee',
        imgPlissee: 'icons/arten/doppelplissee.svg',
        imgRollos: 'icons/arten/doppelplissee.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: false,
      },
      {
        id: 7,
        namePlissee: '',
        nameRollos: 'XL-Rollos',
        imgPlissee: 'icons/arten/rollo_xl.svg',
        imgRollos: 'icons/arten/rollo_xl.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
      {
        id: 8,
        namePlissee: 'Plissee ohne Bohren',
        nameRollos: 'Rollo ohne Bohren',
        imgPlissee: 'icons/arten/ohne_bohren.svg',
        imgRollos: 'icons/arten/ohne_bohren.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,

      },
      {
        id: 9,
        namePlissee: 'Modelltypen',
        nameRollos: 'Modelltypen',
        imgPlissee: 'icons/arten/modelltypen.svg',
        imgRollos: 'icons/arten/modelltypen.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 10,
        namePlissee: 'Ersatzteile',
        nameRollos: 'Ersatzteile',
        imgPlissee: 'icons/arten/ersatzteile.svg',
        imgRollos: 'icons/arten/ersatzteile.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
    ],
  },
  {
    id: 2,
    name: 'Farbe',
    subItems: [
      {
        id: 1,
        namePlissee: 'Weiß',
        nameRollos: 'Weiß',
        imgPlissee: 'icons/farben/weiss.png',
        imgRollos: 'icons/farben/weiss_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 2,
        namePlissee: 'Beige',
        nameRollos: 'Beige',
        imgPlissee: 'icons/farben/beige.png',
        imgRollos: 'icons/farben/beige_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 3,
        name: 'Blau',
        imgPlissee: 'icons/farben/blau.png',
        imgRollos: 'icons/farben/blau_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 4,
        name: 'Braun',
        imgPlissee: 'icons/farben/braun.png',
        imgRollos: 'icons/farben/braun_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 5,
        name: 'Orange',
        imgPlissee: 'icons/farben/orange.png',
        imgRollos: 'icons/farben/orange_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 6,
        name: 'Lila',
        imgPlissee: 'icons/farben/lila.png',
        imgRollos: 'icons/farben/lila_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 7,
        name: 'Grau',
        imgPlissee: 'icons/farben/grau.png',
        imgRollos: 'icons/farben/grau_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 8,
        name: 'Schwarz',
        imgPlissee: 'icons/farben/schwarz.png',
        imgRollos: 'icons/farben/schwarz_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 9,
        name: 'Gelb',
        imgPlissee: 'icons/farben/gelb.png',
        imgRollos: 'icons/farben/gelb_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 10,
        name: 'Grün',
        imgPlissee: 'icons/farben/gruen.png',
        imgRollos: 'icons/farben/gruen_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 11,
        name: 'Rot',
        imgPlissee: 'icons/farben/rot.png',
        imgRollos: 'icons/farben/rot_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 12,
        name: 'Alle Farben',
        imgPlissee: 'icons/farben/alle_farben.png',
        imgRollos: 'icons/farben/alle_farben_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
    ],
  },
  {
    id: 3,
    name: 'Raum',
    subItems: [
      {
        id: 1,
        name: 'Küche',
        desc: 'abwischbar & dekorativ',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-kueche-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-kueche-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
      {
        id: 2,
        name: 'Schlafzimmer',
        desc: 'energiesparend & dunkel',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-schlafzimmer-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-schlafzimmer-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
      {
        id: 3,
        name: 'Badezimmer',
        desc: 'feuchtraumgeeignet & blickdicht',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-bad-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-bad-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
      {
        id: 4,
        name: 'Kinderzimmer',
        desc: 'abdunkelnd & farbenfroh',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-kinderzimmer-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-kinderzimmer-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
      {
        id: 5,
        name: 'Büro',
        desc: 'bildschirmgeeignet',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-buero-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-buero-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
      {
        id: 6,
        name: 'Wohnzimmer',
        desc: 'gemütlich & lichtdurchlässig',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-wohnzimmer-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-wohnzimmer-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
    ],
  },
  {
    id: 4,
    name: 'Eigenshaft',
    subItems: [
      {
        id: 1,
        name: 'Reinigung feucht',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__feucht_abwischbar.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__feucht_abwischbar.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: true,
      },
      {
        id: 2,
        name: 'Reinigung nass',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__nass_abwischbar.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__nass_abwischbar.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
      {
        id: 3,
        name: 'Handwäsche (30°C)',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften_rl_waschbar_30.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften_rl_waschbar_30.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
      {
        id: 4,
        name: 'Schmutzabweisend',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__schmutzabweisend.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__schmutzabweisend.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: true,
        rollos: false,
      },
      {
        id: 5,
        name: 'Verdunkelung',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__verdunkelung.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__verdunkelung.svg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
      {
        id: 4,
        name: 'Hitzeschutz',
        imgPlissee: 'icons/farben/alle_farben_rollo.png',
        imgRollos: 'icons/farben/alle_farben_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
      {
        id: 5,
        name: 'Verdunkelung',
        imgPlissee: 'icons/farben/alle_farben_rollo.png',
        imgRollos: 'icons/farben/alle_farben_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
      {
        id: 6,
        name: 'Sichtschutz',
        imgPlissee: 'icons/farben/alle_farben_rollo.png',
        imgRollos: 'icons/farben/alle_farben_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
      {
        id: 7,
        name: 'Bildschirmarbeitsplatz',
        imgPlissee: 'icons/farben/alle_farben_rollo.png',
        imgRollos: 'icons/farben/alle_farben_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
      {
        id: 8,
        name: 'Feuchtraumgeeignet',
        imgPlissee: 'icons/farben/alle_farben_rollo.png',
        imgRollos: 'icons/farben/alle_farben_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
      {
        id: 9,
        name: 'Schwer entflammbar',
        imgPlissee: 'icons/farben/alle_farben_rollo.png',
        imgRollos: 'icons/farben/alle_farben_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
      {
        id: 10,
        name: 'Sonnenschutz',
        imgPlissee: 'icons/farben/alle_farben_rollo.png',
        imgRollos: 'icons/farben/alle_farben_rollo.png',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
        plissee: false,
        rollos: true,
      },
    ],
  },
  {
    id: 5,
    name: 'Konfigurator',
    subItems: [
    ],
  },
]

export default menuItems
