const menuItems = [
  {
    id: 1,
    name: 'Art',
    subItems: [
      {
        id: 1,
        namePlissee: 'Plissee nach Maß',
        nameRollos: 'Rollos nach Maß',
        imgPlissee: 'icons/arten/plissee_nach_mass.svg',
        imgRollos: 'icons/arten/plissee_nach_mass.svg',
        linkPlissee: '/plissee/modell/wunschmass',
        linkRollos: '/rollo/modell/wunschmass',
        plissee: true,
        rollos: true,
      },
      {
        id: 2,
        namePlissee: 'Cosimo %',
        nameRollos: 'Cosimo',
        imgPlissee: 'icons/arten/cosimo.svg',
        imgRollos: 'icons/arten/cosimo.svg',
        linkplissee: '/plissee/modell/cosimo',
        linkRollos: '',
        plissee: true,
        rollos: false,
      },
      {
        id: 3,
        namePlissee: 'Cosiflor',
        nameRollos: 'Cosiflor',
        imgPlissee: 'icons/arten/cosiflor.svg',
        imgRollos: 'icons/arten/cosiflor.svg',
        linkplissee: '/plissee/modell/cosiflor',
        linkRollos: '',
        plissee: true,
        rollos: false,
      },
      {
        id: 4,
        namePlissee: 'Decomatic',
        nameRollos: 'Decomatic',
        imgPlissee: 'icons/arten/decomatic.svg',
        imgRollos: 'icons/arten/decomatic.svg',
        linkPlissee: '/plissee/modell/decomatic',
        linkRollos: '',
        plissee: true,
        rollos: false,
      },
      {
        id: 5,
        namePlissee: 'Wabenplissee',
        nameRollos: 'Wabenplissee',
        imgPlissee: 'icons/arten/wabenplissee.svg',
        imgRollos: 'icons/arten/wabenplissee.svg',
        linkPlissee: '/plissee/modell/wabenplissee',
        linkRollos: '/plissee/modell/wabenplissee',
        plissee: true,
        rollos: false,
      },
      {
        id: 6,
        namePlissee: 'Doppelplissee',
        nameRollos: 'Doppelplissee',
        imgPlissee: 'icons/arten/doppelplissee.svg',
        imgRollos: 'icons/arten/doppelplissee.svg',
        linkPlissee: '/plissee/modell/doppelplissee',
        linkRollos: '',
        plissee: true,
        rollos: false,
      },
      {
        id: 7,
        namePlissee: '',
        nameRollos: 'XL-Rollos',
        imgPlissee: 'icons/arten/rollo_xl.svg',
        imgRollos: 'icons/arten/rollo_xl.svg',
        linkPlissee: '',
        linkRollos: '/rollo/modell/xl',
        plissee: false,
        rollos: true,
      },
      {
        id: 8,
        namePlissee: 'Plissee ohne Bohren',
        nameRollos: 'Rollo ohne Bohren',
        imgPlissee: 'icons/arten/ohne_bohren.svg',
        imgRollos: 'icons/arten/ohne_bohren.svg',
        linkPlissee: '/plissee/modell/ohne-bohren',
        linkRollos: '/rollo/modell/ohne-bohren',
        plissee: true,
        rollos: true,
      },
      {
        id: 9,
        namePlissee: 'Modelltypen',
        nameRollos: 'Modelltypen',
        imgPlissee: 'icons/arten/modelltypen.svg',
        imgRollos: 'icons/arten/modelltypen.svg',
        linkPlissee: '/plissee/modell/typ',
        linkRollos: '/rollo/modell/typ',
        plissee: true,
        rollos: true,
      },
      {
        id: 10,
        namePlissee: 'Ersatzteile',
        nameRollos: 'Ersatzteile',
        imgPlissee: 'icons/arten/ersatzteile.svg',
        imgRollos: 'icons/arten/ersatzteile.svg',
        linkPlissee: '/ersatzteile',
        linkRollos: '/ersatzteile',
        plissee: true,
        rollos: true,
      },
    ],
  },
  {
    id: 2,
    name: 'Farbe',
    subItems: [
      {
        id: 1,
        namePlissee: 'Weiß',
        nameRollos: 'Weiß',
        imgPlissee: 'icons/farben/weiss.png',
        imgRollos: 'icons/farben/weiss_rollo.png',
        linkPlissee: '/plissee/farbe/weiss',
        linkRollos: '/rollo/farbe/weiss',
        plissee: true,
        rollos: true,
      },
      {
        id: 2,
        namePlissee: 'Beige',
        nameRollos: 'Beige',
        imgPlissee: 'icons/farben/beige.png',
        imgRollos: 'icons/farben/beige_rollo.png',
        linkPlissee: '/plissee/farbe/beige',
        linkRollos: '/rollo/farbe/beige',
        plissee: true,
        rollos: true,
      },
      {
        id: 3,
        namePlissee: 'Blau',
        nameRollos: 'Blau',
        imgPlissee: 'icons/farben/blau.png',
        imgRollos: 'icons/farben/blau_rollo.png',
        linkPlissee: '/plissee/farbe/blau',
        linkRollos: '/rollo/farbe/blau',
        plissee: true,
        rollos: true,
      },
      {
        id: 4,
        namePlissee: 'Braun',
        nameRollos: 'Braun',
        imgPlissee: 'icons/farben/braun.png',
        imgRollos: 'icons/farben/braun_rollo.png',
        linkPlissee: '/plissee/farbe/braun',
        linkRollos: '/rollo/farbe/braun',
        plissee: true,
        rollos: true,
      },
      {
        id: 5,
        namePlissee: 'Orange',
        nameRollos: 'Orange',
        imgPlissee: 'icons/farben/orange.png',
        imgRollos: 'icons/farben/orange_rollo.png',
        linkPlissee: '/plissee/farbe/orange',
        linkRollos: '/rollo/farbe/orange',
        plissee: true,
        rollos: true,
      },
      {
        id: 6,
        namePlissee: 'Lila',
        nameRollos: 'Lila',
        imgPlissee: 'icons/farben/lila.png',
        imgRollos: 'icons/farben/lila_rollo.png',
        linkPlissee: '/plissee/farbe/lila',
        linkRollos: '/rollo/farbe/lila',
        plissee: true,
        rollos: true,
      },
      {
        id: 7,
        namePlissee: 'Grau',
        nameRollos: 'Grau',
        imgPlissee: 'icons/farben/grau.png',
        imgRollos: 'icons/farben/grau_rollo.png',
        linkPlissee: '/plissee/farbe/grau',
        linkRollos: '/rollo/farbe/grau',
        plissee: true,
        rollos: true,
      },
      {
        id: 8,
        namePlissee: 'Schwarz',
        nameRollos: 'Schwarz',
        imgPlissee: 'icons/farben/schwarz.png',
        imgRollos: 'icons/farben/schwarz_rollo.png',
        linkPlissee: '/plissee/farbe/schwarz',
        linkRollos: '/rollo/farbe/schwarz',
        plissee: true,
        rollos: true,
      },
      {
        id: 9,
        namePlissee: 'Gelb',
        nameRollos: 'Gelb',
        imgPlissee: 'icons/farben/gelb.png',
        imgRollos: 'icons/farben/gelb_rollo.png',
        linkPlissee: '/plissee/farbe/gelb',
        linkRollos: '/rollo/farbe/gelb',
        plissee: true,
        rollos: true,
      },
      {
        id: 10,
        namePlissee: 'Grün',
        nameRollos: 'Grün',
        imgPlissee: 'icons/farben/gruen.png',
        imgRollos: 'icons/farben/gruen_rollo.png',
        linkPlissee: '/plissee/farbe/gruen',
        linkRollos: '/rollo/farbe/gruen',
        plissee: true,
        rollos: true,
      },
      {
        id: 11,
        namePlissee: 'Rot',
        nameRollos: 'Rot',
        imgPlissee: 'icons/farben/rot.png',
        imgRollos: 'icons/farben/rot_rollo.png',
        linkPlissee: '/plissee/farbe/rot',
        linkRollos: '/rollo/farbe/rot',
        plissee: true,
        rollos: true,
      },
      {
        id: 12,
        namePlissee: 'Alle Farben',
        nameRollos: 'Alle Farben',
        imgPlissee: 'icons/farben/alle_farben.png',
        imgRollos: 'icons/farben/alle_farben_rollo.png',
        linkPlissee: '/plissee/farbe',
        linkRollos: '/rollo/farbe',
        plissee: true,
        rollos: true,
      },
    ],
  },
  {
    id: 3,
    name: 'Raum',
    subItems: [
      {
        id: 1,
        name: 'Küche',
        desc: 'abwischbar & dekorativ',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-kueche-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-kueche-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
      {
        id: 2,
        name: 'Schlafzimmer',
        desc: 'energiesparend & dunkel',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-schlafzimmer-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-schlafzimmer-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
      {
        id: 3,
        name: 'Badezimmer',
        desc: 'feuchtraumgeeignet & blickdicht',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-bad-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-bad-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
      {
        id: 4,
        name: 'Kinderzimmer',
        desc: 'abdunkelnd & farbenfroh',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-kinderzimmer-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-kinderzimmer-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
      {
        id: 5,
        name: 'Büro',
        desc: 'bildschirmgeeignet',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-buero-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-buero-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
      {
        id: 6,
        name: 'Wohnzimmer',
        desc: 'gemütlich & lichtdurchlässig',
        imgPlissee: 'rooms_plissee/medium-bilder/plissee-wohnzimmer-medium.jpg',
        imgRollos: 'rooms_plissee/medium-bilder/rollo-wohnzimmer-medium.jpg',
        linkPlissee: 'link plissee',
        linkRollos: 'link rollos',
      },
    ],
  },
  {
    id: 4,
    name: 'Eigenshaft',
    subItems: [
      {
        id: 1,
        namePlissee: 'Reinigung feucht',
        nameRollos: 'Reinigung feucht',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__feucht_abwischbar.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__feucht_abwischbar.svg',
        linkPlissee: '/plissee/eigenschaft/feucht-abwischbar',
        linkRollos: '/rollo/eigenschaft/feucht-abwischbar',
        plissee: true,
        rollos: true,
      },
      {
        id: 2,
        namePlissee: 'Reinigung nass',
        nameRollos: 'Reinigung nass',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__nass_abwischbar.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__nass_abwischbar.svg',
        linkPlissee: '/plissee/eigenschaft/nass-abwischbar',
        linkRollos: '/rollo/eigenschaft/nass-abwischbar',
        plissee: false,
        rollos: true,
      },
      {
        id: 3,
        namePlissee: 'Handwäsche (30°C)',
        nameRollos: 'Handwäsche (30°C)',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften_rl_waschbar_30.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften_rl_waschbar_30.svg',
        linkPlissee: '/plissee/eigenschaft/handwaesche',
        linkRollos: '/rollo/eigenschaft/verdunkelung',
        plissee: true,
        rollos: true,
      },
      {
        id: 4,
        namePlissee: 'Schmutzabweisend',
        nameRollos: 'Schmutzabweisend',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__schmutzabweisend.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__schmutzabweisend.svg',
        linkPlissee: '/plissee/eigenschaft/schmutzabweisend',
        linkRollos: '/rollo/eigenschaft/schmutzabweisend',
        plissee: true,
        rollos: false,
      },
      {
        id: 5,
        namePlissee: 'Hitzeschutz',
        nameRollos: 'Hitzeschutz',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__hitzeschutz.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__hitzeschutz.svg',
        linkPlissee: '/plissee/eigenschaft/hitzeschutz',
        linkRollos: '/rollo/eigenschaft/hitzeschutz',
        plissee: true,
        rollos: false,
      },
      {
        id: 6,
        namePlissee: 'Verdunkelung',
        nameRollos: 'Verdunkelung',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__verdunkelung.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__verdunkelung.svg',
        linkPlissee: '/plissee/eigenschaft/verdunkelung',
        linkRollos: '/rollo/eigenschaft/verdunkelung',
        plissee: true,
        rollos: true,
      },
      {
        id: 7,
        namePlissee: 'Sichtschutz',
        nameRollos: 'Sichtschutz',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__transparent_halb.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__transparent_halb.svg',
        linkPlissee: '/plissee/eigenschaft/sichtschutz',
        linkRollos: '/rollo/eigenschaft/sichtschutz',
        plissee: true,
        rollos: true,
      },
      {
        id: 8,
        namePlissee: 'Bildschirmarbeitsplatz',
        nameRollos: 'Bildschirmarbeitsplatz',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften_rl_bildschirmarbeitsplatz.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften_rl_bildschirmarbeitsplatz.svg',
        linkPlissee: '/plissee/eigenschaft/bildschirmarbeitsplatz',
        linkRollos: '/rollo/eigenschaft/bildschirmarbeitsplatz',
        plissee: true,
        rollos: true,
      },
      {
        id: 9,
        namePlissee: 'Feuchtraumgeeignet',
        nameRollos: 'Feuchtraumgeeignet',
        imgPlissee: 'icons/misc/noun_242903.svg',
        imgRollos: 'icons/misc/noun_242903.svg',
        linkPlissee: '/plissee/eigenschaft/feuchtraumgeeignet',
        linkRollos: '/rollo/eigenschaft/feuchtraumgeeignet',
        plissee: true,
        rollos: true,
      },
      {
        id: 10,
        namePlissee: 'Schwer entflammbar',
        nameRollos: 'Schwer entflammbar',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__schwer_entflammbar.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__schwer_entflammbar.svg',
        linkPlissee: '/plissee/eigenschaft/schwer-entflammbar',
        linkRollos: '/rollo/eigenschaft/schwer-entflammbar',
        plissee: true,
        rollos: true,
      },
      {
        id: 11,
        namePlissee: 'Sonnenschutz',
        nameRollos: 'Sonnenschutz',
        imgPlissee: 'icons/eigenschaften/stoffeigenschaften__sonnenschutz.svg',
        imgRollos: 'icons/eigenschaften/stoffeigenschaften__sonnenschutz.svg',
        linkPlissee: '/plissee/eigenschaft/sonnenschutz',
        linkRollos: '/rollo/eigenschaft/sonnenschutz',
        plissee: true,
        rollos: true,
      },
    ],
  },
  {
    id: 5,
    name: 'Konfigurator',
    subItems: [
    ],
  },
]

export default menuItems
